### ISSUE TITLE
point plane contact springs at non 0 degree orientations

### ISSUE THREAD

**Issue by bencannell** [tkoziara/parmec#6]
Hi @tkoziara (mention @stevebrasier),

I think there may be a bug in parmec when attempting to define a point - plane contact spring where "point1" and "point2" are not aligned with the global coordinate system axes.

I've attached two example files:

[45deg_1xdirect.txt](https://github.com/tkoziara/parmec/files/1837757/45deg_1xdirect.txt)
This models a direct contact spring (non point-plane) between two particles. This model behaves as expected.

[45deg_1xpntpln.txt](https://github.com/tkoziara/parmec/files/1837754/45deg_1xpntpln.txt)
This models direct contact via a point-plane spring. This model is expected to behave in the same manner as "45deg_1xdirect.txt" however it doesn't. Visualising the positions of the particles and spring in Paraview suggests that the spring is not positioned correctly:
 ![spring_image](https://user-images.githubusercontent.com/29304199/37774484-393998b4-2dd8-11e8-8af6-ec8a354c4e2b.jpg)

I would expect the visualisation of the blue spring to be located on the 45 degree line between the black particles.

I am using changeset version be9b202 of parmec.

What do you think?

Best regards,

Ben

**Comment by bencannell** [comment]
Hi @tkoziara 

Have you had a chance to look into this yet?

Many thanks,

Ben

**Comment by tkoziara** [comment]
Looking today and on:)

**Comment by bencannell** [comment]
Thank you for the update :)

**Comment by tkoziara** [comment]
You can provide your csv writer class 'CsvSeries': it's not online:)  In the meantime I am working around it...

**Comment by bencannell** [comment]
Ah sorry! I've sent you a personal email...

**Comment by tkoziara** [comment]
Ben,
I looked into this and so far it seems to be just a matter of applying the springs and setting up the model in a suitable way. Have a look at the attached two files: there are changes:)

[45deg_1xdirect_tk1.zip](https://github.com/tkoziara/parmec/files/1915030/45deg_1xdirect_tk1.zip)
[45deg_1xpntpln.zip](https://github.com/tkoziara/parmec/files/1915031/45deg_1xpntpln.zip)
In the first file I have changes the second spring point to be (1, 0, 0) instead of (1, 1, 0); I also made
the same change for the fixed spring direction: changed it from (1, 1, 0) to (1, 0, 0); In the second file I moved the first spring point from (0, 0, 0) to (0.1, 0, 0);
In both files there are no particle restrains, but optionally one can remove all rotations;

One thing to keep in mind that a two-point spring with a fixed direction will maintain that fixed direction of the spring regardless of the motion of particles. On the other hand in the point-to-plane contact spring model the contact plane is co-rotated with the second particle. If there is some eccentricity between the spring points and particle mass centres this will make a significant difference (after the springs have been engaged) as particles will begin to rotate in different ways. This is why in the supplied files you can restrain rotations. You will see that without this restrained a small drift along dy begins to build up post-impact for the contact plane model.

I hope that this explanation and examples will shed some light onto this for you:) I can have a further and deeper look - please let me know in case that would be needed.
Best regards:)
Tomek

**Comment by bencannell** [comment]
Thank you for the feedback @tkoziara. In hindsight, this was a poor attempt on my behalf at narrowing down the issue we were having with point-plane spring models "exploding", which you managed to fix in fb66998.

Best regards:)

Ben
